import {writeFileSync} from "node:fs"
import {isDefined, panic} from "@opendaw/lib-std"
import {PointerTypes} from "@opendaw/lib-box"
import {AnyField, FieldRecord, Schema} from "./schema"

// Emits the Rust box-schema registry consumed by the `boxgraph` reader. Unlike the TS emitter
// (one class file per box), Rust gets ONE `registry.rs` building a `name -> field-schema` map.
// Only serialization-relevant data is emitted: field key -> type, array length, nested objects.
// Ignored (UI/validation only): constraints, units, defaults, pointer rules, value curves, tags.

const rustFieldType = <E extends PointerTypes>(field: AnyField<E>): string => {
    switch (field.type) {
        case "int32":
            return "FieldType::Int32"
        case "float32":
            return "FieldType::Float32"
        case "boolean":
            return "FieldType::Boolean"
        case "string":
            return "FieldType::String"
        case "bytes":
            return "FieldType::Bytes"
        case "pointer":
            return "FieldType::Pointer"
        case "field":
            return "FieldType::Hook" // Field.hook: a pointer-target vertex with no serialized value
        case "array":
            return `FieldType::Array {element: Box::new(${rustFieldType(field.element)}), length: ${field.length}}`
        case "object":
            return `FieldType::Object(${rustSchema(field.class.fields)})`
        default:
            return panic(`cannot map field type to Rust: ${field.type}`)
    }
}

const rustSchema = <E extends PointerTypes>(fields: FieldRecord<E>): string => {
    // Deprecated fields are not written by the TS serializer, and `reserved` keys hold no data —
    // omit both, so the reader skips their bytes as unknown keys (forward-compatible).
    const entries = Object.entries(fields)
        .filter(([_, field]) => field.type !== "reserved" && field.deprecated !== true)
        .map(([key, field]) => `(${Number(key)}u16, ${rustFieldType(field)})`)
    return entries.length === 0 ? "Schema::new()" : `Schema::from([${entries.join(", ")}])`
}

export const writeRustRegistry = <E extends PointerTypes>(schema: Schema<E>, path: string): void => {
    const boxes = schema.boxes
        .map(box => `        ("${box.class.name}".to_string(), ${rustSchema(box.class.fields)}),`)
        .join("\n")
    const usesBox = boxes.includes("Box::new")
    const imports = [
        usesBox ? "use alloc::boxed::Box;" : null,
        "use alloc::string::ToString;",
        "use boxgraph::boxes::Registry;",
        "use boxgraph::field::{FieldType, Schema};"
    ].filter(isDefined).join("\n")
    const body = `// @generated by box-forge — do not edit.
// Regenerate via: npm run build -w @opendaw/studio-forge-boxes
//
// The openDAW box-schema registry (name -> field schema) consumed by the \`boxgraph\` reader.

${imports}

pub fn registry() -> Registry {
    Registry::from([
${boxes}
    ])
}
`
    writeFileSync(path, body)
}
