//! openDAW's box-schema registry for the Rust engine. `registry.rs` is GENERATED by the box-forge
//! (TS) from the same schema that generates the TS box classes — single source, no drift. This
//! crate is the openDAW-specific layer; the generic codec lives in `boxgraph`.

#![cfg_attr(not(test), no_std)]

extern crate alloc;

mod registry;

pub use registry::registry;
